language: python

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  global:
    - CC=gcc-4.9 CXX=g++-4.9

before_install:
  # Upgrade PIP to latest version, in order to support --progres-bar
  - pip install -U pip
  # Manually install torch, and pybind11 since they are required in the setup
  - pip install torch==0.4.1 --progress-bar off
  - pip install pybind11 --progress-bar off

install:
  - python setup.py install

script:
  - python -m unittest torch_baidu_ctc.test

notifications:
  email:
    on_success: change
    on_failure: always
