dist: trusty
sudo: false

language: python

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - CC=gcc-4.9 CXX=g++-4.9

# Add tests with additional compilers
matrix:
  include:
      - python: 3.6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gcc-5
              - g++-5
        env: CC=gcc-5 CXX=g++-5
      - python: 3.6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gcc-5
              - g++-5
        env: CC=gcc-6 CXX=g++-6

before_install:
  # Upgrade PIP to latest version, in order to support --progres-bar
  - pip install -U pip
  # Manually install torch, and pybind11 since they are required in the setup
  - ./travis/install_pytorch.sh
  - pip install pybind11 --progress-bar off

install:
  - python setup.py install

script:
  - python -m unittest torch_baidu_ctc.test

notifications:
  email:
    on_success: change
    on_failure: always
