dist: xenial
sudo: true
language: python

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

# Test all Python version with the latest PyTorch.
env:
  global:
    - CC=gcc-4.9 CXX=g++-4.9
  matrix:
    - TORCH_PIP_PACKAGE=torch

# Test other PyTorch/Python combinations.
# matrix:
#   include:
#     - python: 3.6
#       env: TORCH_PIP_PACKAGE="torch==1.0.0"
#     - python: 3.6
#       env: TORCH_PIP_PACKAGE="torch==1.0.1"

before_install:
  # Upgrade PIP to latest version, in order to support --progres-bar
  - pip install -U pip
  # Install prerequisites.
  - pip install --progress-bar off -r <(sed -r 's/^torch.*$//g;/^$/d' requirements.txt)
  - pip install $TORCH_PIP_PACKAGE --progress-bar off

install:
  - python setup.py install

script:
  - cd /tmp
  - python -m unittest torch_baidu_ctc.test

notifications:
  email:
    on_success: change
    on_failure: always
